title: Robert DeRienzo's Blog

description: This is a collection of things that have at one point piqued my interest.

author:
  name: Robert DeRienzo
  email: rlderienzo@gmail.com

show_excerpts: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/RobertLD" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/robert-derienzo-179ba9196/" }


google_analytics: G-BHSYV5JQGN


# # Minima: custom header links
# header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md
