title: Robert DeRienzo's Blog
description: This is a collection of things that have at one point piqued my interest.
show_excerpts: true

plugins:
  - jekyll-remote-theme 
remote_theme: jekyll/minima

minima:
  skin: dark


# # Minima: custom header links
# header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md
