title: RobertLD's Ramblings
description: A collection of personal thoughts and ideas
show_excerpts: true

plugins:
  - jekyll-remote-theme 
remote_theme: jekyll/minima

minima:
  skin: dark


# # Minima: custom header links
# header_pages:
#   - _pages/frontpage.md
#   - _pages/about.md
#   - _pages/archive.md
