lsi: false
safe: true
incremental: false
highlighter: rouge

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-minimal
title: RobertLD's Ramblings
description: A collection of personal thoughts and ideas


